name: Build and Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      # Build and push frontend
      - name: Build Frontend
        run: |
          cd frontend
          docker build -t frontend:${{ github.sha }} .
          docker tag frontend:${{ github.sha }} ghcr.io/vineeta05/frontend-service:${{ github.sha }}
          docker tag frontend:${{ github.sha }} ghcr.io/vineeta05/frontend-service:latest
          docker push ghcr.io/<username>/frontend-service:${{ github.sha }}
          docker push ghcr.io/<username>/frontend-service:latest

      # Build and push backend
      - name: Build Backend
        run: |
          cd backend
          docker build -t backend:${{ github.sha }} .
          docker tag backend:${{ github.sha }} ghcr.io/vineeta05/backend-service:${{ github.sha }}
          docker tag backend:${{ github.sha }} ghcr.io/vineeta05/backend-service:latest
          docker push ghcr.io/<username>/backend-service:${{ github.sha }}
          docker push ghcr.io/<username>/backend-service:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - uses: actions/checkout@v4

      - name: Login to OpenShift
        run: |
          oc login ${{ secrets.OPENSHIFT_URL }} \
            --username=${{ secrets.OPENSHIFT_USER }} \
            --password=${{ secrets.OPENSHIFT_PASSWORD }} \
            --insecure-skip-tls-verify=true

      - name: Apply OpenShift YAMLs
        run: |
          oc apply -f openshift/
